lib/events_board_web/router.ex
defmodule EventsBoardWeb.Router do
  use EventsBoardWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventsBoardWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EventsBoardWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/events", EventController
    resources "/users", UserController
    get "/users/photo/:id", UserController, :photo
    resources "/sessions", SessionController,
      only: [:create, :delete], singleton: true
    resources "/comments", CommentController
    resources "/invites", InviteController
  end

  # Other scopes may use custom stacks.
  # scope "/api", EventsBoardWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventsBoardWeb.Telemetry
    end
  end
end

lib/events_board_web/views/layout_view.ex
defmodule EventsBoardWeb.LayoutView do
  use EventsBoardWeb, :view
end

lib/events_board_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>EventsBoard · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header class="container">
      <div class="row">
        <%= if get_flash(@conn, :info) do %>
          <p class="alert alert-info" role="alert">
            <%= get_flash(@conn, :info) %>
          </p>
        <% end %>
        <%= if get_flash(@conn, :error) do %>
          <p class="alert alert-danger" role="alert">
            <%= get_flash(@conn, :error) %>
          </p>
        <% end %>
      </div>
      <div class="row">
        <div class="col my-2">
          <span><%= link "Home", to: '/' %></span>
        </div>
        <%= if @conn.assigns[:current_user] do %>
          <div class="col my-2" >
              User: <%= @current_user.name %> |
              <%= link("Logout", to: Routes.session_path(@conn, :delete),
                method: :delete) %>
          </div>
        <% else %>
          <div class="col">
            <%= form_for @conn, Routes.session_path(@conn, :create),
            [class: "form-inline"], fn f -> %>
              <%= text_input f, :email, class: "form-control", placeholder: "Email" %>
              <%= submit "Login", class: "btn btn-secondary" %>
            <% end %>
          </div>
          <div class="col my-2">
            <%= link "Register", to: Routes.user_path(@conn, :new), style: "float: right" %>
          </div>
        <% end %>
      </div>
    </header>
    <main role="main" class="container">
        <%= @inner_content %>
    </main>
  </body>
</html>