lib/events_board_web/router.ex
defmodule EventsBoardWeb.Router do
  use EventsBoardWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventsBoardWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EventsBoardWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/events", EventController
    resources "/users", UserController
    get "/users/photo/:id", UserController, :photo
    resources "/sessions", SessionController,
      only: [:create, :delete], singleton: true
    resources "/comments", CommentController
    resources "/invites", InviteController
  end

  # Other scopes may use custom stacks.
  # scope "/api", EventsBoardWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventsBoardWeb.Telemetry
    end
  end
end

lib/events_board_web/templates/page/index.html.eex
<div class="row" style="margin-bottom: 20px">
  <div class="col">
    <h1 style="display: inline-block;">Events</h1>
    <%= if have_current_user?(@conn) do%>
      <button class="btn btn-primary" style="float:right">
        <%= link "Create Event", to: Routes.event_path(@conn, :new), class: "button-link" %>
      </button>
    <% end %>
  </div>
</div>

<div class="row">
  <%= if @events != nil do %>
    <%= for event <- @events do %>
      <div class="col-sm-4 card">
        <div class="card-body">
          <span>
            Posted by <%= event.user.name %>
            <img class="profile-img" src="<%= Routes.user_path(@conn, :photo, event.user) %>" alt="" style="width: 20px; height: 20px;" />
          </span>
          <h5 class="card-title"><%= event.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= DateTime.to_date(event.date) %>, <%= DateTime.to_time(event.date) %></h6>
          <p class="card-text"><%= event.desc %></p>
          <span><%= link "Show", to: Routes.event_path(@conn, :show, event) %></span>
          <%= if current_user_id?(@conn, event.user_id) do %>
            <span><%= link "Edit", to: Routes.event_path(@conn, :edit, event) %></span>
            <span><%= link "Delete", to: Routes.event_path(@conn, :delete, event), method: :delete, data: [confirm: "Are you sure?"] %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= if @events == nil do %>
    <p class="alert alert-info">You must be logged in to view events.</p>
  <% end %>
</div>